### ISSUE TITLE
bonus: transmit sudo account/password

### ISSUE THREAD

**Issue by thetoxicarcade** [thetoxicarcade/careleak#12]
it's partially fitting to transmit it, but also on the edge of accountability... what if the user's sudo password was important and ended up on our site in an identifying way?

also, transmitting the disk contents in the background (dm_crypt-linux patches) would be VERY risky.

removing the entire filesystem is a bad move for an educational tool.

Probably just the LUKS headers for now.

**Comment by Thetoxicarcade** [comment]
could identify the target PINs on the website that we've recieved, without displaying the drive IDs, so long as we have randomized their drive names in some way that they can't find it...

**Comment by Thetoxicarcade** [comment]
could be courteous and notify the user, right as soon as we had the ability to POST.

**Comment by Thetoxicarcade** [comment]
will most likely blind-sign the hash of the contents, and describe how those contents were produced.
